export const AUTH_SUCCESS = 'auth_success'
export const ERROR_MSG = 'error_msg'
export const RECEIVE_USER = 'receive_user'
export const RESET_USER = 'reset_user'
export const RECEIVE_USER_LIST = 'receive_user_list'
export const RECEIVE_MSG_LIST = 'receive_msg_list'
export const RECEIVE_MSG = 'receive_msg'
export const MSG_READ = 'msg_read'
